### ISSUE TITLE
plc-applicator with own key broken

### ISSUE THREAD

**Issue by ledlamp** [mary-ext/boat#2]
input is hex
![Something went wrong: Error: invalid private key, expected hex or 32 bytes, got object](https://github.com/user-attachments/assets/ba9707bf-5cd2-461c-a533-6e8532edb62c)

**Comment by laanwj** [comment]
It looks like this error is shown when the hex is not 64 exactly characters (32 bytes).

**Comment by ledlamp** [comment]
Hmm. That's odd. I generated private key with `goat crypto generate`, and then I converted it to hex in node repl:

```
var {multibaseToBytes} = require("@atproto/crypto")
var key = multibaseToBytes("<my multibase key>")
Buffer.from(key).toString("hex")
```

Why's it 68 chars?

**Comment by laanwj** [comment]
There's a 2-byte (4 hex char) prefix that determines the kind of key (`8126` for secp256k1, `8626` for secp256r1). Stripping that will give you the bare key.

**Comment by mary-ext** [comment]
Yup, the input asks for *raw/bare keys*. I should make that clearer.

I do plan on adding multibase support later (which does insist on having those byte prefix), it does seem to be the intended format to save them in anyway (I used raw hex because that's what the PDS had them in, so the tool was convenient way for selfhosters because you just copy the keys you already have)

**Comment by mary-ext** [comment]
See https://github.com/mary-ext/boat/issues/1#issuecomment-2562165695
